[package]
name = "wasm_config_dev"
version = "0.1.3"
authors = ["Changqing Shen"]
edition = "2024"

[dependencies]
log = "0.4.28"
proxy-wasm = "0.2.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

